/*
 * CHANGE LOG - keep only last 5 threads
 * 
 * on-line resources
 */
using Gravity.Drivers.Mock.WebDriver;
using Gravity.Services.Comet.Engine.Extensions;
using Gravity.Services.Comet.Engine.Plugins;
using Gravity.Services.DataContracts;
using Newtonsoft.Json;
using OpenQA.Selenium;
using System;
using System.Collections.Generic;

namespace Gravity.Services.ActionPlugins.Tests
{
    public abstract class ActionTests
    {
        /// <summary>
        /// Set all static members of this action tests.
        /// </summary>
        static ActionTests()
        {
            Types = Utilities.GetTypes();
        }

        /// <summary>
        /// Creates a new instance of this action tests.
        /// </summary>
        protected ActionTests()
        {
            // setup: web automation
            var configuration = new EngineConfiguration
            {
                ElementSearchingTimeout = 100,
                PageLoadTimeout = 100
            };
            WebAutomation = new WebAutomation { EngineConfiguration = configuration };
            WebDriver = new MockWebDriver();
        }

        /// <summary>
        /// Gets the types repository loaded for all tests in this domain.
        /// </summary>
        public static IEnumerable<Type> Types { get; }

        /// <summary>
        /// Gets a basic web automation instance for all tests in this domain
        /// </summary>
        public WebAutomation WebAutomation { get; }

        /// <summary>
        /// Gets a new MockWebDriver instance or the last instance generated by ActionFactory.
        /// </summary>
        public MockWebDriver WebDriver { get; set; }

        /// <summary>
        /// Executes an action plug-in of the provided type.
        /// </summary>
        /// <typeparam name="T">The type of action which will be executed.</typeparam>
        public void ExecuteAction<T>() where T : ActionPlugin
        {
            ExecuteAction<T>(by: default, actionRule: string.Empty, capabilities: null);
        }

        /// <summary>
        /// Executes an action plug-in of the provided type.
        /// </summary>
        /// <typeparam name="T">The type of action which will be executed.</typeparam>
        /// <param name="actionRule">ActionRule JSON from which to create an ActionRule instance.</param>
        public void ExecuteAction<T>(string actionRule)
            where T : ActionPlugin
        {
            ExecuteAction<T>(by: default, actionRule: actionRule, capabilities: null);
        }

        /// <summary>
        /// Executes an action plug-in of the provided type.
        /// </summary>
        /// <typeparam name="T">The type of action which will be executed.</typeparam>
        /// <param name="capabilities">MockWebDriver capabilities by which to create the MockWebDriver of this action.</param>
        public void ExecuteAction<T>(IDictionary<string, object> capabilities)
            where T : ActionPlugin
        {
            ExecuteAction<T>(by: default, actionRule: string.Empty, capabilities: capabilities);
        }

        /// <summary>
        /// Executes an action plug-in of the provided type.
        /// </summary>
        /// <typeparam name="T">The type of action which will be executed.</typeparam>
        /// <param name="by">WebElement instance on which to perform the action.</param>
        public void ExecuteAction<T>(By by) where T : ActionPlugin
        {
            ExecuteAction<T>(by: by, actionRule: string.Empty, capabilities: null);
        }

        /// <summary>
        /// Executes an action plug-in of the provided type.
        /// </summary>
        /// <typeparam name="T">The type of action which will be executed.</typeparam>
        /// <param name="by">WebElement instance on which to perform the action.</param>
        /// <param name="actionRule">ActionRule JSON from which to create an ActionRule instance.</param>
        public void ExecuteAction<T>(By by, string actionRule)
            where T: ActionPlugin
        {
            ExecuteAction<T>(by: by, actionRule: actionRule, capabilities: null);
        }

        /// <summary>
        /// Executes an action plug-in of the provided type.
        /// </summary>
        /// <typeparam name="T">The type of action which will be executed.</typeparam>
        /// <param name="by">WebElement instance on which to perform the action.</param>
        /// <param name="capabilities">MockWebDriver capabilities by which to create the MockWebDriver of this action.</param>
        public void ExecuteAction<T>(By by, IDictionary<string, object> capabilities)
            where T : ActionPlugin
        {
            ExecuteAction<T>(by: by, actionRule: string.Empty, capabilities: capabilities);
        }

        /// <summary>
        /// Executes an action plug-in of the provided type.
        /// </summary>
        /// <typeparam name="T">The type of action which will be executed.</typeparam>
        /// <param name="actionRule">ActionRule JSON from which to create an ActionRule instance.</param>
        /// <param name="capabilities">MockWebDriver capabilities by which to create the MockWebDriver of this action.</param>
        public void ExecuteAction<T>(string actionRule, IDictionary<string, object> capabilities)
            where T : ActionPlugin
        {
            ExecuteAction<T>(by: default, actionRule: actionRule, capabilities: capabilities);
        }

        /// <summary>
        /// Executes an action plug-in of the provided type.
        /// </summary>
        /// <typeparam name="T">The type of action which will be executed.</typeparam>
        /// <param name="by">WebElement instance on which to perform the action.</param>
        /// <param name="actionRule">ActionRule JSON from which to create an ActionRule instance.</param>
        /// <param name="capabilities">MockWebDriver capabilities by which to create the MockWebDriver of this action.</param>
        public void ExecuteAction<T>(By by, string actionRule, IDictionary<string, object> capabilities)
            where T : ActionPlugin
        {
            // setup
            var _actionRule = GetActionRule(actionRule);
            var action = ActionFactory<T>(WebAutomation, capabilities);

            // execute
            if (by == default)
            {
                action.OnPerform(_actionRule);
                return;
            }
            var element = WebDriver.FindElement(by);
            action.OnPerform(element, _actionRule);
        }

        /// <summary>
        /// Gets an action rule object out of action rule JSON (deserialize).
        /// </summary>
        /// <param name="actionRule">Action rule JSON by which to create an action rule object.</param>
        /// <returns>Action rule object.</returns>
        public static ActionRule GetActionRule(string actionRule)
        {
            if (string.IsNullOrEmpty(actionRule))
            {
                return new ActionRule();
            }
            return JsonConvert.DeserializeObject<ActionRule>(actionRule);
        }

        /// <summary>
        /// Generates an action based on the provided type
        /// </summary>
        /// <typeparam name="T">Action type from which to generate the action.</typeparam>
        /// <param name="webAutomation">Web Automation object by which to generate the action.</param>
        /// <param name="capabilities">Capabilities to add to the action Web Driver instance</param>
        /// <returns>Action plug-in instance of the specified type.</returns>
        public T ActionFactory<T>(WebAutomation webAutomation, IDictionary<string, object> capabilities)
            where T : ActionPlugin
        {
            // setup
            if(capabilities != default)
            {
                WebDriver = WebDriver.ApplyCapabilities(capabilities);
            }

            // generate
            return (T)Activator.CreateInstance(typeof(T), new object[] { WebDriver, webAutomation, Types });
        }
    }
}