using Gravity.Abstraction.WebDriver;
using Gravity.Plugins.Base;
using Gravity.Plugins.Contracts;
using Gravity.Plugins.Engine;
using Gravity.Plugins.Extensions;
using Newtonsoft.Json;
using OpenQA.Selenium;
using OpenQA.Selenium.Extensions;
using OpenQA.Selenium.Mock;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace Gravity.Plugins.Actions.UnitTests.ForBridge
{
    public class AutomationExecutor
    {
        // constants: automation context
        private const string LastReference = "LastReference";
        private const string OnSession = "OnSession";
        private const string Executor = "Executor";
        private const string Factory = "Factory";
        private const string Response = "Response";
        private const string LastPlugin = "LastPlugin";

        // members: settings
        private readonly ParallelOptions parallelOptions;
        private readonly LoginManager loginManager = new LoginManager();

        // members: meta data
        private readonly ConcurrentDictionary<string, OrbitResponse> responses;

        #region *** constructors       ***
        /// <summary>
        /// Creates a new instance of <see cref="Executor"/>.
        /// </summary>
        public AutomationExecutor()
            : this(automation: default)
        { }

        /// <summary>
        /// Creates a new instance of <see cref="Executor"/>.
        /// </summary>
        /// <param name="automation">A collection of <see cref="WebAutomation"/> to execute.</param>
        public AutomationExecutor(WebAutomation automation)
        {
            // setup: members
            responses = new ConcurrentDictionary<string, OrbitResponse>();
            parallelOptions = new ParallelOptions
            {
                MaxDegreeOfParallelism = automation.EngineConfiguration.MaxParallelExecution
            };

            // setup: properties
            Automations = GetAutomations(byAutomation: automation);
            PluginFactory ??= new PluginFactory(automation);

            // setup: login
            loginManager
                .Login(automation.Authentication.UserName, automation.Authentication.Password)
                .GetAwaiter()
                .GetResult();
        }
        #endregion

        #region *** properties         ***
        /// <summary>
        /// Gets a list of all <see cref="IWebDriver"/> in the application domain.
        /// </summary>
        public static IDictionary<string, IWebDriver> Drivers { get; } = new ConcurrentDictionary<string, IWebDriver>();

        /// <summary>
        /// Gets or sets the collection of <see cref="WebAutomation"/> to execute.
        /// </summary>
        public IEnumerable<WebAutomation> Automations { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="Engine.PluginFactory"/> used by this <see cref="AutomationExecutor"/>.
        /// </summary>
        public PluginFactory PluginFactory { get; set; }

        /// <summary>
        /// Gets a collection of <see cref="ComposedResponse"/> generated by this <see cref="AutomationExecutor"/>.
        /// </summary>
        public IDictionary<string, OrbitResponse> Responses => responses;
        #endregion

        #region *** execute automation ***
        /// <summary>
        /// Executes <see cref="Automations"/> collection generated by this instance.
        /// </summary>
        /// <returns><see cref="WebAutomation"/> execution results.</returns>
        public IDictionary<string, OrbitResponse> Execute()
        {
            // iterate automation requests
            Parallel.ForEach(Automations, parallelOptions, (automation) => Execute(automation));

            // process response
            return responses;
        }

        /// <summary>
        /// Executes <see cref="WebAutomation"/> instance.
        /// </summary>
        /// <param name="automation"><see cref="WebAutomation"/> to execute.</param>
        /// <returns><see cref="WebAutomation"/> execution results.</returns>
        public IDictionary<string, OrbitResponse> Execute(WebAutomation automation)
        {
            return Execute(automation, actionRules: automation.Actions);
        }

        /// <summary>
        /// Executes <see cref="WebAutomation"/> instance.
        /// </summary>
        /// <param name="automation"><see cref="WebAutomation"/> to execute.</param>
        /// <param name="actionRules">A collection of <see cref="ActionRule"/> to execute.</param>
        /// <returns><see cref="WebAutomation"/> execution results.</returns>
        public IDictionary<string, OrbitResponse> Execute(WebAutomation automation, IEnumerable<ActionRule> actionRules)
        {
            // setup
            Setup(automation);

            // recursion
            foreach (var action in actionRules)
            {
                Execute(automation, actionRule: action, parameters: Array.Empty<object>());
            }

            // process response
            return responses;
        }

        /// <summary>
        /// Executes <see cref="WebAutomation"/> instance.
        /// </summary>
        /// <param name="automation"><see cref="WebAutomation"/> to execute.</param>
        /// <param name="actionRules">A collection of <see cref="ActionRule"/> to execute.</param>
        /// <param name="parameters">Perform method parameters list excluding <see cref="ActionRule"/> parameter type.</param>
        /// <returns><see cref="WebAutomation"/> execution results.</returns>
        public IDictionary<string, OrbitResponse> Execute(
            WebAutomation automation, IEnumerable<ActionRule> actionRules, object[] parameters)
        {
            // setup
            Setup(automation);

            // recursion
            foreach (var action in actionRules)
            {
                Execute(automation, actionRule: action, parameters);
            }

            // process response
            return responses;
        }

        /// <summary>
        /// Executes an <see cref="ActionRule"/> instance.
        /// </summary>
        /// <param name="automation"><see cref="WebAutomation"/> context by which to execute this <see cref="ActionRule"/>.</param>
        /// <param name="actionRule"><see cref="ActionRule"/> to execute.</param>
        /// <param name="parameters">Perform method parameters list excluding <see cref="ActionRule"/> parameter type.</param>
        public void Execute(WebAutomation automation, ActionRule actionRule, object[] parameters)
        {
            // setup
            var reference = (int)automation.Context[LastReference];
            actionRule.Reference = reference++;
            automation.Context[LastReference] = reference;

            // execution pipeline
            DoExecute(automation, actionRule, parameters);

            // exit condition
            if (!actionRule.Actions.Any())
            {
                return;
            }

            // recursion
            foreach (var action in actionRule.Actions)
            {
                Execute(automation, actionRule: action, parameters);
            }

            // return results
            var composed = (ComposedResponse)automation.Context[Response];
            responses[composed.OnSession] = composed.GetResponse();
        }

        private void DoExecute(WebAutomation automation, ActionRule actionRule, object[] parameters)
        {
            var stopwatch = new Stopwatch();
            stopwatch.Start();
            try
            {
                // setup
                var isOnSession = automation.Context.ContainsKey(OnSession)
                    && !string.IsNullOrEmpty($"{automation.Context[OnSession]}");

                // driver
                var driver = isOnSession
                    ? Drivers[$"{automation.Context[OnSession]}"]
                    : SetupDriver(automation);

                // extract factory
                var factory = automation.Context[Factory] as PluginFactory;

                // execute
                factory.ConstructorParameters = new object[] { automation, driver };
                var plugin = factory.Factor(actionRule).Execute(parameters);

                // update factory
                automation.Context[Factory] = factory;
                automation.Context[LastPlugin] = plugin;
            }
            catch (Exception e) when (e != null)
            {
                AddException(automation, actionRule, e);
            }
            finally
            {
                AddPerformancePoint(automation, actionRule, stopwatch);
                AddResults(automation);
            }
        }

        private void Setup(WebAutomation automation)
        {
            // setup conditions
            var isLastReference = automation.Context.ContainsKey(LastReference);
            var isExecutor = automation.Context.ContainsKey(Executor) && automation.Context[Executor] != default;
            var isFactory = automation.Context.ContainsKey(Factory) && automation.Context[Factory] != default;
            var isResponse = automation.Context.ContainsKey(Response) && automation.Context[Response] != default;

            // setup
            if (!isLastReference)
            {
                automation.Context[LastReference] = 0;
            }
            if (!isExecutor)
            {
                automation.Context[Executor] = this;
            }
            if (!isFactory)
            {
                automation.Context[Factory] = new PluginFactory(automation);
            }
            if (!isResponse)
            {
                automation.Context[Response] = new ComposedResponse(automation);
            }
        }

        private void AddResults(WebAutomation automation)
        {
            // extract composed object
            var composed = automation.Context[Response] as ComposedResponse;
            var plugin = automation.Context.ContainsKey(LastPlugin)
                ? automation.Context[LastPlugin] as Plugin
                : null;

            // setup conditions
            var isOnSession = !string.IsNullOrEmpty(composed.OnSession);

            // apply data
            composed.OnSession = isOnSession ? composed.OnSession : $"{automation.Context[OnSession]}";
            composed.Exceptions.AddRange(plugin?.Exceptions);
            composed.Extractions.AddRange(plugin?.Extractions);
            composed.PerformancePoints.AddRange(plugin?.PerformancePoints);

            // update state
            automation.Context[Response] = composed;
        }

        private void AddPerformancePoint(WebAutomation automation, ActionRule actionRule, Stopwatch stopwatch)
        {
            stopwatch.Stop();

            // setup
            var plugin = automation.Context.ContainsKey(LastPlugin)
                ? automation.Context[LastPlugin] as Plugin
                : null;

            // create performance point
            var point = new OrbitPerformancePoint
            {
                Action = actionRule.ActionType,
                ActionReference = actionRule.Reference,
                RepeatReference = actionRule.RepeatReference,
                Time = stopwatch.Elapsed.TotalMilliseconds
            };

            // attach > update
            plugin.PerformancePoints ??= new ConcurrentBag<OrbitPerformancePoint>();
            plugin.PerformancePoints.Add(point);
            automation.Context[LastPlugin] = plugin;

            stopwatch.Reset();
        }

        private void AddException(WebAutomation automation, ActionRule actionRule, Exception exception)
        {
            // setup
            var plugin = automation.Context.ContainsKey(LastPlugin)
                ? automation.Context[LastPlugin] as Plugin
                : null;

            // create exception
            var orbitException = new OrbitException
            {
                Action = actionRule.ActionType,
                ActionReference = actionRule.Reference
            };
            orbitException.Exception = exception.InnerException ?? exception;

            // attach > update
            plugin.Exceptions ??= new ConcurrentBag<OrbitException>();
            plugin.Exceptions.Add(orbitException);
            automation.Context[LastPlugin] = plugin;
        }
        #endregion

        #region *** utilities          ***
        // generates all web automation to executed, based on the given request(s)
        private IEnumerable<WebAutomation> GetAutomations(WebAutomation byAutomation)
        {
            // exit conditions
            if (byAutomation?.DataSource?.Source == default)
            {
                return new[] { byAutomation };
            }

            // setup
            var dataTable = new DataTable().Load(dataSource: byAutomation.DataSource);
            var automation = JsonConvert.SerializeObject(byAutomation);
            var automations = automation.FromTable(dataTable);

            // add data-rows
            return automations.Select(JsonConvert.DeserializeObject<WebAutomation>);
        }
        #endregion

        #region *** driver factory     ***
        // setup a new or existing web-driver for the current executor instance
        private IWebDriver SetupDriver(WebAutomation automation)
        {
            // default
            if (automation.DriverParams == default || automation.DriverParams.Keys.Count == 0)
            {
                return UpdateState(automation, driver: new MockWebDriver());
            }

            // setup
            var driverParamsJson = JsonConvert.SerializeObject(automation.DriverParams);

            // use existing
            const string PATTERN = @"(?i)(""|')driver(""|'):(\s+)?(""|')[a-z,A-Z]+(""|')";
            var useExisting = !Regex.IsMatch(driverParamsJson, PATTERN, RegexOptions.IgnoreCase);
            if (useExisting)
            {
                return Drivers
                    .FirstOrDefault(k => k.Key.Equals(driverParamsJson, StringComparison.OrdinalIgnoreCase))
                    .Value;
            }

            // create driver
            var driver = new DriverFactory(driverParamsJson).Create();

            // set timeouts
            var p = automation.EngineConfiguration.PageLoadTimeout;
            var e = automation.EngineConfiguration.ElementSearchingTimeout;

            WrappedAction(() => driver.Manage().Timeouts().PageLoad = TimeSpan.FromMilliseconds(p));
            WrappedAction(() => driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromMilliseconds(e));

            // results
            return UpdateState(automation, driver);
        }

        // general try/catch for void action with warning
        private void WrappedAction(Action factory)
        {
            try
            {
                factory.Invoke();
            }
            catch (Exception e) when (e != null)
            {
                // ignore exceptions
            }
        }

        // update state
        private IWebDriver UpdateState(WebAutomation automation, IWebDriver driver)
        {
            // extract session id
            var id = $"{driver.GetSession()}";

            // apply to collection & return current driver
            Drivers[id] = driver;
            automation.Context[OnSession] = id;

            // results
            return driver;
        }
        #endregion
    }
}